name: unit

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unit tests
        run: python3 -m unittest discover -s tests
